version: '3.1'

services:
  messageapp:
    image: messageapp
    container_name: message_app
    build: ./
    volumes:
    - /data/messageapp
    ports:
    - "8082:8082"
    depends_on:
      - postgresqldb
      - kafka-server
    networks:
      - springboot-network
  postgresqldb:
    image: postgres
    container_name: postgres_db
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=messageappdb
    volumes:
    - db-data:/var/lib/postgresql/data/
    networks:
    - springboot-network
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - "2181:2181"
  kafka-server:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-server
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
    - springboot-network
  networks:
    springboot-network:
      driver: bridge
  volumes:
    db-data: